name: ci
on: [ push, workflow_dispatch ]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Run tests
        run: npm install && npm test
